### ISSUE TITLE
Streams with different mbps metadata does not found

### ISSUE THREAD

**Issue by heroku-miraheze** [funcy2267/iptv-rec#1]
py .\iptv-rec.py --host 127.0.0.1 --port 7657 "7 Noticias"
No streams found.

**Comment by funcy2267** [comment]
This is actually problem of unsupported *mbps* type of data, now should be fixed with "minimal parse".

**Comment by funcyme** [comment]
This was actually problem of unsupported `mbps` type of data, now should be fixed with "minimal parse".
